Skip tests with missing requirements
SINTEF/dlite pull request #1032
Opened 2024-12-02 22:34 UTC by jesper-friis

# Description
Skip tests with missing requirements

## Type of change
- [ ] Bug fix & code cleanup
- [ ] New feature
- [ ] Documentation update
- [x] Test update

## Checklist for the reviewer
This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

2024-12-09 13:10 UTC, francescalb requested changes
It is OK to skip tests locally due to missing of imports, but not on github. In this way we may risk to remove dependencies and thus stop testing parts of the code without it being picked up on in the CI/CD workflows. 

If this is to be accepted, we need to have an additional check after ctest, that check that all skipped tests are in the specified list of tests (e.g. mongodb-test cannot run on github)

2024-12-11 14:13 UTC, jesper-friis commented
> It is OK to skip tests locally due to missing of imports, but not on github. In this way we may risk to remove dependencies and thus stop testing parts of the code without it being picked up on in the CI/CD workflows.
> 
> If this is to be accepted, we need to have an additional check after ctest, that check that all skipped tests are in the specified list of tests (e.g. mongodb-test cannot run on github)

It can be implemented with importskip() checking an environment variable. If it is set, the skip will not be accepted.

2024-12-14 14:32 UTC, francescalb commented on bindings/python/testutils.py
> +        regardless of `DLITE_IMPORTSKIP_EXITCODE` is set.
```suggestion
        For packages that depend on external services like postgresql,
        call `importskip()` with `env_exitcode=None` to skip the test
        regardless of whether `DLITE_IMPORTSKIP_EXITCODE` is set or not.
```

2024-12-14 14:33 UTC, francescalb commented on doc/user_guide/environment_variables.md
> +    cannot import a needed module.
```suggestion
  - **DLITE_IMPORTSKIP_EXITCODE**: Exit code from tests that fail to
    load a python module with `importskip()`.  Define this to 1 at
    configure time if you want the tests not to be skipped if they
    cannot import a needed module.
```

2024-12-14 14:37 UTC, francescalb approved these changes
Very nice.

2024-12-14 14:46 UTC, merged